version: 2.1
jobs:
  run_terraform_plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: terraform init
      - run: terraform plan

workflows:
  version: 2
  main:
    jobs:
      - run_terraform_plan:
          context: terraform-sample
