version: 2.1
jobs:
  run_terraform_plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: tfnotifyのインストール
          command: |
            wget https://github.com/mercari/tfnotify/releases/download/v0.6.1/tfnotify_linux_amd64.tar.gz
            tar zxvf tfnotify_linux_amd64.tar.gz
            mv tfnotify /usr/local/bin
     - run:
          name: tfnotifyのテスト
          command: tfnotify
      - run: terraform init
      - run: terraform plan

workflows:
  version: 2
  main:
    jobs:
      - run_terraform_plan:
          context: terraform-sample
