version: 2.1
commands:
  install-tfnotify:
    steps:
      - run:
          name: tfnotifyのインストール
          command: |
              wget https://github.com/mercari/tfnotify/releases/download/v0.6.1/tfnotify_linux_amd64.tar.gz
              tar zxvf tfnotify_linux_amd64.tar.gz
              mv tfnotify /usr/local/bin

jobs:
  run_terraform_plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout

      - install-tfnotify

      - run: terraform init

      - run: terraform validate

      - run: terraform fmt -check -diff -recursive

      - run: terraform plan

  run_terraform_apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout

      - install-tfnotify

      - run: terraform init

      - run: terraform apply

workflows:
  version: 2
  main:
    jobs:
      - run_terraform_plan:
          context: terraform-sample

      - run_terraform_apply:
          context: terraform-sample
          filters:
            branches:
              only: master
